from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1300, 980)
        MainWindow.setMinimumSize(QtCore.QSize(1300, 980))
        MainWindow.setMaximumSize(QtCore.QSize(1300, 1000))
        MainWindow.setStyleSheet("font-family: Calibri;\n"
"font-size: 18px;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.start = QtWidgets.QPushButton(self.centralwidget)
        self.start.setObjectName("start")
        self.gridLayout_2.addWidget(self.start, 0, 0, 1, 1)
        self.stop = QtWidgets.QPushButton(self.centralwidget)
        self.stop.setObjectName("stop")
        self.gridLayout_2.addWidget(self.stop, 0, 1, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_2.addWidget(self.progressBar, 1, 0, 1, 2)
        self.gridLayout_3.addLayout(self.gridLayout_2, 1, 1, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.bboxes = QtWidgets.QTableWidget(self.centralwidget)
        self.bboxes.setObjectName("bboxes")
        self.bboxes.setColumnCount(2)
        self.bboxes.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.bboxes.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.bboxes.setHorizontalHeaderItem(1, item)
        self.gridLayout.addWidget(self.bboxes, 1, 0, 1, 3)
        self.reset = QtWidgets.QPushButton(self.centralwidget)
        self.reset.setObjectName("reset")
        self.gridLayout.addWidget(self.reset, 0, 2, 1, 1)
        self.remove = QtWidgets.QPushButton(self.centralwidget)
        self.remove.setObjectName("remove")
        self.gridLayout.addWidget(self.remove, 0, 1, 1, 1)
        self.add = QtWidgets.QPushButton(self.centralwidget)
        self.add.setObjectName("add")
        self.gridLayout.addWidget(self.add, 0, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 1, 1, 1)
        self.frame = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(900, 800))
        self.frame.setMaximumSize(QtCore.QSize(900, 800))
        self.frame.setAutoFillBackground(False)
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setText("")
        self.frame.setScaledContents(False)
        self.frame.setObjectName("frame")
        self.gridLayout_3.addWidget(self.frame, 0, 0, 2, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.console = QtWidgets.QScrollArea(self.centralwidget)
        self.console.setWidgetResizable(True)
        self.console.setObjectName("console")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1276, 119))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.console.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.console)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1300, 28))
        self.menubar.setObjectName("menubar")
        self.menuNew = QtWidgets.QMenu(self.menubar)
        self.menuNew.setObjectName("menuNew")
        MainWindow.setMenuBar(self.menubar)
        self.menubar.addAction(self.menuNew.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Fluorescent Bead Analyzer"))
        self.start.setText(_translate("MainWindow", "Start"))
        self.stop.setText(_translate("MainWindow", "Stop"))
        item = self.bboxes.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.bboxes.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Coordinates"))
        self.reset.setText(_translate("MainWindow", "Reset"))
        self.remove.setText(_translate("MainWindow", "Remove"))
        self.add.setText(_translate("MainWindow", "Add"))
        self.menuNew.setTitle(_translate("MainWindow", "New"))